### ISSUE TITLE
Create Menubar class

### ISSUE THREAD

**Issue by hrw** [libyui/libyui#158]
The only way to create something resembling menu in libyui is using YMenuButtons. It looks good on ncurses frontend but terribly on Gtk/Qt one.

Have you considered creating YMenuBar class? To use GtkMenuBar/QMenuBar and draw a line of YMenuButtons for ncurses backend.

Would make app look more like other Gtk/Qt apps.

**Comment by ancorgs** [comment]
It's not pure libYUI, but YaST has some menus configured here:
https://github.com/yast/yast-autoinstallation/blob/master/src/include/autoinstall/conftree.rb#L374

Result:
![menu](https://user-images.githubusercontent.com/3638289/73525938-6f8e8c80-4410-11ea-8df8-d147b8e16775.png)

**Comment by anaselli** [comment]
I would like to propose a minimal, aesthetic change. That has no impacts on libyui implementation, just on Qt and Gtk plugins. See picture below (Qt one is the first):

![dnfdragora Qt Menu](https://user-images.githubusercontent.com/1303486/79635894-fcc1c180-8173-11ea-88b8-1c60d46e144f.png)

![dnfdragora Gtk Menu](https://user-images.githubusercontent.com/1303486/79635896-03503900-8174-11ea-86af-862f952a2d95.png)

The change just remove the border to menu button. I think that could be a good compromise, what do you think. 
I will provide PR later eventually.

**Comment by Conan-Kudo** [comment]
It's an improvement, though I wonder why libyui can't provide a proper menubar class? Is it because of ncurses?

**Comment by papoteur-mga** [comment]
Yes, Angelo, this is a better look, buttons doesn't more look as separated.

**Comment by anaselli** [comment]
> It's an improvement, though I wonder why libyui can't provide a proper menubar class? Is it because of ncurses?

well [YMenuButton](https://github.com/libyui/libyui/blob/master/src/YMenuButton.h) is the libyui abstraction. So it's provided something for menus, plugins should implement it better at least for GUI, while TUI can be acceptable.
BTW if you have an idea how it can be provided i can add it to MGA Plugin first...

**Comment by Conan-Kudo** [comment]
Perhaps in the MGA plugin, we have a `YMGAMenuBar` class that uses the native [QMenuBar](https://doc.qt.io/qt-5/qmenubar.html) (Qt) and [GtkMenuBar](https://developer.gnome.org/gtk3/stable/GtkMenuBar.html) (Gtk3). For ncurses, this could be implemented using the [`menus` library in ncurses](https://tldp.org/HOWTO/NCURSES-Programming-HOWTO/menus.html).

**Comment by anaselli** [comment]
FWIW I'm working on it into MGA plugin [Gtk](https://github.com/manatools/libyui-mga/blob/master/screenshots/MenuBar-Gtk.png), [Qt](https://github.com/manatools/libyui-mga/blob/master/screenshots/MenuBar-Qt.png) and of course [ncurses](https://github.com/manatools/libyui-mga/blob/master/screenshots/MenuBar-ncurses.png). Not finished yet bu in progress :)

**Comment by anaselli** [comment]
A new dnfdragora [2.0.3](https://github.com/manatools/dnfdragora/releases/tag/2.0.3) has been released, please tell me if we can close this issue

**Comment by shundhammer** [comment]
There is minimalistic support for menu bars in the wizard widget, but that is an optional one and not available for NCurses.

We are planning to add a real menu bar soon; even though this is strictly speaking against the philosophy of libyui: A simplified widget toolkit for simple system administration tasks that are typically wizard-driven. Anything as complex requiring many different actions in the same window that it would need a menu bar is actually beyond that scope; that's a document-centric user interface rather than the wizard-driven workflows that we usually have.

Having said that, there are still fringe cases where those philosohpies overlap. But please understand that there will probably still be limitations, partly being limited by what can reasonably be done by a text-based interface like libyui-ncurses and the level of fine-control (or rather the lack of it) that a very abstract API like libyui offers.

**Comment by anaselli** [comment]
I see, if you're interested in see what we've done already into mga plugin have a look at the [WIP TODO](https://github.com/manatools/libyui-mga/blob/master/TODO.md) and of course if you've time to do it, also testing it :)

**Comment by lslezak** [comment]
It has been added recently to the libyui, see these pulls:

- PR for libyui: https://github.com/libyui/libyui/pull/169
- PR for the Qt UI: https://github.com/libyui/libyui-qt/pull/130
- PR for the NCurses UI: 
  - https://github.com/libyui/libyui-ncurses/pull/97 (basic implementation)
  - https://github.com/libyui/libyui-ncurses/pull/99 (some improvements)

So let's close this one. :smiley:

**Comment by anaselli** [comment]
Let's recall this issue here

> The only way to create something resembling menu in libyui is using YMenuButtons. It looks good on ncurses frontend but terribly on Gtk/Qt one.

**terribly on Gtk/Qt one**

> Have you considered creating YMenuBar class? To use GtkMenuBar/QMenuBar and draw a line of YMenuButtons for ncurses backend.

> Would make app look more like other Gtk/Qt apps.

 **Would make app look more like other Gtk/Qt apps**

I'm not sure this issue has been really fixed (well it is using [mga plugin](https://github.com/manatools/libyui-mga) really), the request was to have a menubar working for Gtk and Qt apps, here i seem to read that has been developed for _Qt and ncurses_.
 
Anyway I'll take my time to test the implementation and add my comments on other related issues
