### ISSUE TITLE
Build issue with suse-samba-tools that appeared in the past month

### ISSUE THREAD

**Issue by unquietwiki** [libyui/libyui#6]
Hey there. I was able to build, but not run, **suse-samba-tools** about 6 weeks ago. I revisited the situation; even switched over to using OpenSUSE from Debian/Ubuntu, and there's a git-ref issue that's crept in, and now obstructing builds. It wasn't clear to me what release tag I should try to fix the code to use, or how I'd go about getting it to use the Ruby gem that was mentioned here in the README. Any help would be duly appreciated, and I hope everyone is doing alright. Thanks!

https://github.com/suse-samba-tools/admin-tools/issues/5

**Comment by shundhammer** [comment]
Some quick info up front:

https://github.com/libyui/libyui-old/pull/178
https://github.com/libyui/libyui-old/issues/177

(If any link in any of those gives you a 404, try replacing "https://github.com/libyui/libyui/" with "https://github.com/libyui/libyui-old/"

**Comment by shundhammer** [comment]
Most of the .cmake files that were installed to the system .cmake directory are gone. To keep your CMake build environment working, I suggest you use your find_curses.patch not only for Debian, but for SUSE (or generally everywhere) as well.

But actually, you shouldn't need any of this when you simply use the latest libyui which does all that transparently. You seem to force certain versions of libyui subpackages; that will be problematic since we also bumped the SO version.

**Comment by unquietwiki** [comment]
Thanks @shundhammer for the clarification! This makes sense of what errors I was seeing when I was trying to use the software.

**Comment by shundhammer** [comment]
Also check if you really need this at all; if that application is _using_ libyui, it should not need to link against libncurses. Check your final application with `ldd -u`; you may be _overlinking_ it, i.e. link more shared libs than you really need.

Please notice that libyui loads its NCurses plug-in dynamically on demand; it's only that plugin that needs to link against libncurses, not your application. Unless, of course, you use libncurses (the non-libyui part!) directly, in which case the plain CMake FindLibrary() from your find_ncurses.patch is the way to go.
