### ISSUE TITLE
GCC 13: src/YMenuWidget.h:98:18: error: 'virtual void YMenuWidget::addItem(YItem*)' was hidden [-Werror=overloaded-virtual=]

### ISSUE THREAD

**Issue by marxin** [libyui/libyui#80]
Please fix the following error:

```
$ osc co devel:libraries:libyui/libyui
$ cd $_
$ osc build --alternative-project devel:gcc:next
...
[    4s] In file included from /home/abuild/rpmbuild/BUILD/libyui-4.4.3/libyui/src/YMenuButton.h:28,
[    4s]                  from /home/abuild/rpmbuild/BUILD/libyui-4.4.3/libyui/src/YDialogSpy.cc:42:
[    4s] /home/abuild/rpmbuild/BUILD/libyui-4.4.3/libyui/src/YMenuWidget.h:98:18: error: 'virtual void YMenuWidget::addItem(YItem*)' was hidden [-Werror=overloaded-virtual=]
[    4s]    98 |     virtual void addItem( YItem * item_disown );
[    4s]       |                  ^~~~~~~
[    4s] /home/abuild/rpmbuild/BUILD/libyui-4.4.3/libyui/src/YMenuButton.h:68:17: note:   by 'YMenuItem* YMenuButton::addItem(const std::string&, const std::string&)'
[    4s]    68 |     YMenuItem * addItem( const std::string & label,
[    4s]       |                 ^~~~~~~
```

**Comment by marxin** [comment]
May I please remind this @shundhammer, @lslezak ?

**Comment by shundhammer** [comment]
I just put it into our to-do queue for the current / upcoming sprint.

Sorry, we were a bit busy with HiDPI problems:

- https://github.com/libyui/libyui/pull/81
- https://github.com/yast/yast-installation/pull/1057

**Comment by shundhammer** [comment]
Related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=20423 ?

**Comment by marxin** [comment]
> The derived `YMenuButton` class declares a non-virtual method `addItem()` with a different signature: With two `std::string` arguments, and with a `YMenuItem` pointer as its return type:
> 
> https://github.com/libyui/libyui/blob/master/libyui/src/YMenuButton.h#L68-L69
> 
> ```c++
>     YMenuItem * addItem( const std::string & label,
>                          const std::string & iconName = "" );
> ```
> 
> So, what's the problem here?

Yes, it's mentioned as one of the problem in:
https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2009/n2928.htm

> How can one _shadow_ the other? They both have different signatures. It should be clear for the compiler to determine which one to call in what context.

So the signature change is not enough, please rename the function or preserve the signature defined in base class.

**Comment by shundhammer** [comment]
That really sounds like a compiler problem to me. That warning is bogus and triggers way too easily.

**Comment by shundhammer** [comment]
I really don't want to mess up the API because of a compiler being oversensitive. Looks more like a use case for this:

- https://gcc.gnu.org/onlinedocs/gcc/Diagnostic-Pragmas.html
- https://stackoverflow.com/questions/925179/selectively-remove-a-warning-message-using-gcc

  about like this:

```C++
#pragma GCC diagnostic ignored "-Woverloaded-virtual"
```

**Comment by marxin** [comment]
Sure, please use the pragma to mitigate the warning if you don't like it ;)

**Comment by shundhammer** [comment]
PR: https://github.com/libyui/libyui/pull/84

**Comment by marxin** [comment]
Can you please make a new release (or cherry-pick this change) and make a submit request against `openSUSE:Factory`?

**Comment by shundhammer** [comment]
This went to YaST:Head long ago, which means an automatic submission to Factory. It's even in Leap 15.4 and in SLE-15 SP4.

https://github.com/libyui/libyui/blob/master/package/libyui.changes#L26-L31

**Comment by marxin** [comment]
Oh, you are correct. There are actually the same Werrors, but seen at different locations. Lemme create a new issue for that.

**Comment by jwakely** [comment]
> So, what's the problem here? How can one _shadow_ the other? They both have different signatures. 

The derived class has a function with the same name, which means it hides the one with the same name in the base class. If the base class function is virtual, and you have a function with the same name and a different signature in a derived class, that's often a mistake. Why would you want to hide the base class' virtual function making it inaccessible?

```c++
struct Base {
  virtual void foo() { }
};
struct Derived : Base {
  virtual void foo(int) { }
};
int main() {
  Derived d;
  d.foo(); // error: Base::foo() is hidden by overload
}
```

> It should be clear for the compiler to determine which one to call in what context.

Yes, it's very clear: only the one in the derived class can be called. And that's probably a mistake, which is why GCC gives a warning. Clang gives the same warning btw:

```
$ clang++  v.cc -Wall
v.cc:5:16: warning: 'Derived::foo' hides overloaded virtual function [-Woverloaded-virtual]
  virtual void foo(int) { }
               ^
v.cc:2:16: note: hidden overloaded virtual function 'Base::foo' declared here: different number of parameters (0 vs 1)
  virtual void foo() { }
               ^
1 warning generated.
```

And the EDG compiler:

```
$ edg -c v.cc
"v.cc", line 5: warning: function "Base::foo()" is hidden by "Derived::foo" --
          virtual function override intended?
    virtual void foo(int) { }
                 ^
```

The reason all compilers warn about this is because it's highly questionable code. If you really want to hide the base function, there are ways to do it that make it clear you're doing it on purpose. If you don't want to hide the base function, well then you wrote a bug and that's exactly why this deserves a warning. Either way, adding a using-declaration for the base function makes the intent clear and avoids the warnings.

**Comment by mvidner** [comment]
(I'll comment here even though it's closed, because it's the first mention of the problem in our codebase.)

> Related to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=20423 ? "Warning -Woverloaded-virtual triggers to often"

Thanks @shundhammer for mentioning that. Let me quote the report and notice the last paragraph:

> ```cxx
> class Foo
> {
> public: virtual void Func(int);
>         virtual void Func(int, int);
> };
> 
> class Baz: public Foo
> {
> public: virtual void Func(int, int);
> };
> ```
> 
> When compiled with gcc40 I get:
> 
> warntest.cpp:4: warning: 'virtual void Foo::Func(int)' was hidden
> warntest.cpp:10: warning:   by 'virtual void Baz::Func(int, int)'
> 
> The warning is triggered only if I try to overload one of the two
> Func in Foo. _If both Func are declared in Baz no warning is issued._
> 

IMHO that is the best solution: redeclaring `void addItem( YItem *)` in `YMenuButton` (the subclass). The library users do not _need_ it but it does the job of telling the compiler that it should not warn about the `YItem*` form getting lost.

I've first added this to `YMenuButton`

```cxx
    virtual void addItem( YItem * item_disown ) override { YMenuWidget::addItem(item_disown); }
```

but then I noticed Jonathan saying "*adding a using-declaration for the base function*" and managed to deduce this, before finding [a description of using-declarations](https://en.cppreference.com/w/cpp/language/using_declaration)

```cxx
    using YMenuWidget::addItem;
```

with that, silencing the warning is no longer needed.

**Comment by mvidner** [comment]
BTW, 

> And the EDG compiler:

TIL, that's the [Edison Design Group](https://www.edg.com/faq) compiler, IIUC a commercial frontend-only product.
